### PR TITLE
CD-23: Support PWA Drupal module

### PR DESCRIPTION
**Pull request by rupl**
Similar to #1 the [Web Manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest) in this theme is hardcoded, which doesn't play well with other modules in a Drupal implementation that also want to customize the manifest.

Additionally, the manifest.json is very unlikely to be used without a valid Service Worker, which this theme lacks. Supporting the [PWA Drupal module](https://www.drupal.org/project/pwa) is an easy way to achieve basic offline support and "Add to Homescreen" prompts without having to worry about authoring and maintaining a custom Service Worker.

There is no negative effect when the PWA module is disabled or not yet installed. It's a pure enhancement which does not affect basic website functionality.

### Testing

- Download/Enable PWA module
- Enable `ocha_basic` and set to default
- Clear all caches
- In Chrome DevTools, open the **Application** tab and in the left-hand column click **Manifest**
- Manifest should claim to live at `sites/default/files/pwa/manifest.json`
- Inspect the manifest metadata in the right-hand column and compare to reference screenshot:

pwa-ocha_basic

### CODE REVIEW

**Comment by rupl** [comment]
whoops, the screenshot is slightly out of date. the theme color should show as `#026CB6`

**Comment by rupl** [comment]
So, I found a major D7 theming no-no while testing the PWA module and have included the fix in this PR. The `$scripts` var had been moved to the bottom of the template and was appearing _after_ `$page-bottom` which is almost guaranteed to break any Drupal implementation that uses the JS `Drupal` object _and_ uses the `scope: footer` setting of [`drupal_add_js()`](https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_add_js/7.x)

I've restored `$scripts` to the `<head>` and we can assemble some docs or an official procedure for moving scripts to bottom if people want this by default. I would generally just recommend [AdvAgg](https://www.drupal.org/project/advagg) and will be happy to write some docs in a follow-up.

**Comment by emmajane** [comment]
Docs can go into https://docs.google.com/document/d/1d-OA78JhGWHPULDQAGPKwLPtOL_vHnTQLGnW2JaD-Gw/edit

**Comment by rupl** [comment]
Upon reading the docs I realize the PWA module is not yet able to be used on official deployments (lacks official stable release + not yet covered by security). However as mentioned in the OP it's purely optional, so we can still move ahead here despite the non-eligible status of the soft dependency.

**Comment by emmajane** [comment]
👍 also: if we can support getting PWA to a 1.0, that'd be cool too.

**Comment by rupl** [comment]
wow that's swell! I did actually reclassify one support request as a bug after testing on the theme but barring that it's very close. I'll keep it as a low priority todo for when I'm running out of tickets, and will immediately change the security coverage.

**Comment by emmajane** [comment]
Yay!

**Pull request merged**
